markdown: kramdown
kramdown:
  input: GFM
pygments: false
permalink: none
url: http://designwithfontforge.com
title: Design With FontForge
subtitle: A book about how to create new typefaces using FontForge
